# Generated by Django 5.2.6 on 2025-11-04 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time the payment status was updated.",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount in the currency's smallest unit (e.g., cents for USD).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the payment record was created.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="usd",
                help_text="ISO 4217 currency code (e.g., usd, eur).",
                max_length=10,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("requires_payment_method", "Requires Payment Method"),
                    ("requires_confirmation", "Requires Confirmation"),
                    ("requires_action", "Requires Action"),
                ],
                default="pending",
                help_text="Current status of the payment.",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent",
            field=models.CharField(
                blank=True,
                help_text="Payment Intent ID if using Payment Intents API.",
                max_length=255,
                null=True,
                verbose_name="Stripe Payment Intent ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                help_text="Unique identifier for the Stripe Checkout Session.",
                max_length=255,
                unique=True,
                verbose_name="Stripe Checkout Session ID",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="The user who initiated this payment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["stripe_session_id"], name="payments_pa_stripe__ab8e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_b8a300_idx"
            ),
        ),
    ]
