# Generated by Django 5.2.6 on 2025-09-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
