# Generated by Django 5.2.6 on 2025-11-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_itemportfolio_options_alter_user_email"),
        ("projects", "0003_project_image_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="projectapplication",
            options={
                "verbose_name": "project application",
                "verbose_name_plural": "project applications",
            },
        ),
        migrations.AlterModelOptions(
            name="projectassignment",
            options={
                "verbose_name": "project assignment",
                "verbose_name_plural": "project assignments",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="budget"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.clientprofile",
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="image path"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="CREATED",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="cover_letter",
            field=models.TextField(blank=True, verbose_name="cover letter"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.freelancerprofile",
                verbose_name="freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="proposed_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="proposed payment",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="agreed_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="agreed payment",
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="freelancer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.freelancerprofile",
                verbose_name="freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="role",
            field=models.CharField(blank=True, max_length=100, verbose_name="role"),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("INVITED", "Invited"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("REMOVED", "Removed"),
                ],
                default="INVITED",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
