# Generated by Django 5.2.6 on 2025-11-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_itemportfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemportfolio",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this portfolio item",
                null=True,
                upload_to="portfolio/",
            ),
        ),
    ]
