# Generated by Django 5.2.6 on 2025-11-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_itemportfolio_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemportfolio",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a portfolio item image",
                null=True,
                upload_to="portfolios/",
            ),
        ),
    ]
