# Generated by Django 5.2.6 on 2025-11-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_itemportfolio_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemportfolio",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
