# Generated by Django 4.2.23 on 2025-09-08 22:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('programming', 'Programación'), ('design', 'Diseño'), ('business', 'Negocios'), ('marketing', 'Marketing'), ('career', 'Desarrollo de Carrera'), ('freelancing', 'Freelancing'), ('technology', 'Tecnología'), ('other', 'Otros')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.PositiveIntegerField(help_text='Duración en horas')),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='Fecha y hora programada para la sesión', null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BOOKED', 'Reservada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='AVAILABLE', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Link de reunión (Zoom, Meet, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales para la sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee_sessions', to='core.freelancerprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='core.freelancerprofile')),
            ],
            options={
                'verbose_name': 'Sesión de Mentoría',
                'verbose_name_plural': 'Sesiones de Mentoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación de 1 a 5 estrellas')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.freelancerprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mentorship.mentorshipsession')),
            ],
            options={
                'verbose_name': 'Reseña de Mentoría',
                'verbose_name_plural': 'Reseñas de Mentoría',
            },
        ),
    ]
