# Generated by Django 4.2.23 on 2025-09-08 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipWishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshipsession')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_items', to='services.wishlist')),
            ],
            options={
                'verbose_name': 'Item de Mentoría en Wishlist',
                'verbose_name_plural': 'Items de Mentorías en Wishlist',
                'unique_together': {('wishlist', 'mentorship')},
            },
        ),
        migrations.CreateModel(
            name='MentorshipCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_items', to='services.cart')),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorshipsession')),
            ],
            options={
                'verbose_name': 'Item de Mentoría en Carrito',
                'verbose_name_plural': 'Items de Mentorías en Carrito',
                'unique_together': {('cart', 'mentorship')},
            },
        ),
    ]
