# Generated by Django 5.2.6 on 2025-09-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itemportfolio'),
        ('mentorship_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipsession',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientprofile'),
        ),
    ]
