# Generated by Django 5.2.6 on 2025-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_session', '0002_alter_mentorshipsession_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
