# Generated by Django 5.2.6 on 2025-11-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_itemportfolio_options_alter_user_email"),
        ("mentorship_session", "0003_mentorshipsession_image_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentorshipsession",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Mentorship Session",
                "verbose_name_plural": "Mentorship Sessions",
            },
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                help_text="How long the session will last in minutes",
                verbose_name="Duration (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="image_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Image Path"
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="mentee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorship_bookings",
                to="core.clientprofile",
                verbose_name="Mentee",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentorship_sessions",
                to="core.freelancerprofile",
                verbose_name="Mentor",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="start_time",
            field=models.DateTimeField(
                help_text="When the session will begin", verbose_name="Start Time"
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("no_show", "No Show"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="topic",
            field=models.CharField(
                help_text="The main topic of the mentorship session",
                max_length=255,
                verbose_name="Topic",
            ),
        ),
        migrations.AlterField(
            model_name="mentorshipsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
