# Generated by Django 5.2.6 on 2025-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microservice',
            name='delivery_time',
            field=models.PositiveIntegerField(help_text='Delivery time in days'),
        ),
    ]
