# Generated by Django 5.2.6 on 2025-11-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microservices", "0003_microservice_image_path"),
        ("microservices", "0004_convert_delivery_time"),
    ]

    operations = []
