# Generated by Django 5.2.6 on 2025-11-04 21:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_itemportfolio_options_alter_user_email"),
        ("microservices", "0005_merge_20251101_2257"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="microservice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "MicroService",
                "verbose_name_plural": "MicroServices",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Enter a unique category name.",
                max_length=100,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name.",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="category",
            field=models.ForeignKey(
                help_text="Select the category that best fits this service.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="microservices",
                to="microservices.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="delivery_time",
            field=models.PositiveIntegerField(
                help_text="How many days it takes to deliver the final work.",
                verbose_name="Delivery Time (days)",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="description",
            field=models.TextField(
                help_text="Describe what you offer, what’s included, and any requirements.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="freelancer",
            field=models.ForeignKey(
                help_text="The freelancer offering this microservice.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="microservices",
                to="core.freelancerprofile",
                verbose_name="Freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="image_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the uploaded service image.",
                max_length=500,
                null=True,
                verbose_name="Image Path",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this service from the marketplace.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Fixed price for this service in USD.",
                max_digits=10,
                verbose_name="Price (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="title",
            field=models.CharField(
                help_text="A clear, compelling title for your service.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="microservice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddConstraint(
            model_name="microservice",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", Decimal("0.00"))),
                name="microservice_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="microservice",
            constraint=models.CheckConstraint(
                condition=models.Q(("delivery_time__gte", 1)),
                name="microservice_delivery_time_positive",
            ),
        ),
    ]
